// <auto-generated />
using System;
using LibraryAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibraryAPI.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20210727114611_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LibraryAPI.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookID");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            BookName = "Book 1"
                        });
                });

            modelBuilder.Entity("LibraryAPI.Models.BookBorrowingRequest", b =>
                {
                    b.Property<int>("BookBorrowingRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminApproved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateRequest")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalUserRequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookBorrowingRequestID");

                    b.ToTable("BookBorrowingRequest");
                });

            modelBuilder.Entity("LibraryAPI.Models.BookBorrowingRequestDetail", b =>
                {
                    b.Property<int>("BookBorrowingRequestID")
                        .HasColumnType("int");

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<int?>("number")
                        .HasColumnType("int");

                    b.HasKey("BookBorrowingRequestID", "BookID");

                    b.HasIndex("BookID");

                    b.ToTable("BookBorrowingRequestDetail");
                });

            modelBuilder.Entity("LibraryAPI.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Category 1"
                        });
                });

            modelBuilder.Entity("LibraryAPI.Models.NormalUser", b =>
                {
                    b.Property<int>("NormalUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NormalUserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalUserPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NormalUserID");

                    b.ToTable("NormalUser");

                    b.HasData(
                        new
                        {
                            NormalUserID = 1,
                            NormalUserEmail = "1",
                            NormalUserName = "user 1",
                            NormalUserPassword = "1"
                        });
                });

            modelBuilder.Entity("LibraryAPI.Models.SuperUser", b =>
                {
                    b.Property<int>("SuperUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SuperUserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuperUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuperUserPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SuperUserID");

                    b.ToTable("SuperlUser");

                    b.HasData(
                        new
                        {
                            SuperUserID = 1,
                            SuperUserEmail = "1",
                            SuperUserName = "admin 1",
                            SuperUserPassword = "1"
                        });
                });

            modelBuilder.Entity("LibraryAPI.Models.BookBorrowingRequestDetail", b =>
                {
                    b.HasOne("LibraryAPI.Models.BookBorrowingRequest", "BookBorrowingRequest")
                        .WithMany("BorrowingRequestDetails")
                        .HasForeignKey("BookBorrowingRequestID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("LibraryAPI.Models.Book", "Book")
                        .WithMany("BorrowingRequestDetails")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("BookBorrowingRequest");
                });

            modelBuilder.Entity("LibraryAPI.Models.Book", b =>
                {
                    b.Navigation("BorrowingRequestDetails");
                });

            modelBuilder.Entity("LibraryAPI.Models.BookBorrowingRequest", b =>
                {
                    b.Navigation("BorrowingRequestDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
